init:
  - git config --global core.autocrlf true

install:
  - choco install pretzel -y
  - choco install pretzel.scriptcs -y

build_script:
  - "\"C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.0\\Framework\\v4.0\\fsi\" BuildAndTests.fsx build"

test_script:
  - "\"C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.0\\Framework\\v4.0\\fsi\" BuildAndTests.fsx tests"

artifacts:
  - path: artifacts\MarkdigEngine.zip
    name: MarkdigEngine.zip

deploy:
  - provider: GitHub
    auth_token:
      secure: Prb/lsKP5VK0hN58Bw2RiU8uyi1kpNEleEOjybPQQQlSH3tXR7ru6s8J4I7hx/Um
    artifact: MarkdigEngine.zip
    description: "## Second release\r\n\r\n[Updated for Markdig 0.7](https://github.com/laedit/Pretzel.Markdig/pull/1) thanks to [thoemmi](https://github.com/thoemmi)."
    on:
      appveyor_repo_tag: true
